--npc task
local collect_task = {
	{prefab = "ash", num = 20, level = 1},
	{prefab = "log", num = 10, level = 1},
	{prefab = "charcoal", num = 10, level = 1},
	{prefab = "flint", num = 20, level = 1},
	{prefab = "nitre", num = 15, level = 1},
	{prefab = "rocks", num = 20, level = 1},
	{prefab = "marble", num = 10, level = 1},
	{prefab = "goldnugget", num = 10, level = 1},
	{prefab = "ice", num = 10, level = 1},
	{prefab = "petals_evil", num = 10, level = 1},
	{prefab = "cutreeds", num = 10, level = 1},
	{prefab = "boards", num = 10, level = 1},
	{prefab = "cutstone", num = 10, level = 1},
	{prefab = "papyrus", num = 8, level = 1},
	{prefab = "pigskin", num = 8, level = 1},
	{prefab = "manrabbit_tail", num = 8, level = 1},
	{prefab = "spidergland", num = 10, level = 1},
	{prefab = "honeycomb", num = 1, level = 1},
	{prefab = "tentaclespots", num = 5, level = 1},
	{prefab = "mosquitosack", num = 10, level = 1},
	{prefab = "lightninggoathorn", num = 1, level = 1},
	{prefab = "glommerfuel", num = 1, level = 1},
	{prefab = "nightmarefuel", num = 10, level = 1},
	{prefab = "transistor", num = 4, level = 1},
	{prefab = "poop", num = 10, level = 1},
	{prefab = "houndstooth", num = 10, level = 1},
	{prefab = "stinger", num = 10, level = 1},
	{prefab = "boneshard", num = 10, level = 1},
	{prefab = "spidereggsack", num = 1, level = 1},
	{prefab = "feather_crow", num = 4, level = 1},
	{prefab = "feather_robin", num = 4, level = 1},
	{prefab = "feather_robin_winter", num = 2, level = 1},
	{prefab = "feather_canary", num = 2, level = 1},
	{prefab = "beefalowool", num = 10, level = 1},
	{prefab = "beardhair", num = 5, level = 1},
	{prefab = "foliage", num = 10, level = 1},

	{prefab = "waxpaper", num = 2, level = 2},
	{prefab = "moonrocknugget", num = 4, level = 2},
	{prefab = "lightbulb", num = 20, level = 2},
	{prefab = "lureplantbulb", num = 1, level = 2},
	{prefab = "slurtleslime", num = 10, level = 2},
	{prefab = "slurtle_shellpieces", num = 10, level = 2},
	{prefab = "slurper_pelt", num = 2, level = 2},
	{prefab = "fossil_piece", num = 1, level = 2},
	{prefab = "seeds", num = 20, level = 2},
	{prefab = "red_cap", num = 10, level = 2},
	{prefab = "green_cap", num = 5, level = 2},
	{prefab = "blue_cap", num = 5, level = 2},
	{prefab = "trunk_summer", num = 1, level = 2},
	{prefab = "trunk_winter", num = 1, level = 2},
	{prefab = "pumpkin", num = 2, level = 2},
	{prefab = "dragonfruit", num = 2, level = 2},
	{prefab = "watermelon", num = 2, level = 2},
	{prefab = "smallmeat", num = 6, level = 2},
	{prefab = "drumstick", num = 4, level = 2},
	{prefab = "monstermeat", num = 20, level = 2},
	{prefab = "plantmeat", num = 2, level = 2},
	{prefab = "bird_egg", num = 20, level = 2},
	{prefab = "tallbirdegg", num = 1, level = 2},
	--{prefab = "fish", num = 5, level = 2},
	{prefab = "froglegs", num = 5, level = 2},
	{prefab = "batwing", num = 2, level = 2},
	{prefab = "pondfish", num = 5, level = 2},
	{prefab = "honey", num = 5, level = 2},
	{prefab = "heatrock", num = 1, level = 2},
	{prefab = "beefalohat", num = 1, level = 2},
	{prefab = "strawhat", num = 1, level = 2},
	{prefab = "armorgrass", num = 1, level = 2},
	{prefab = "blueprint", num = 1, level = 2},

	{prefab = "goatmilk", num = 2, level = 3},
	{prefab = "butter", num = 1, level = 3},
	{prefab = "bedroll_furry", num = 1, level = 3},
	--{prefab = "deer_antler", num = 1, level = 3},
	{prefab = "butterflymuffin", num = 2, level = 3},
	{prefab = "frogglebunwich", num = 2, level = 3},
	{prefab = "honeyham", num = 2, level = 3},
	{prefab = "dragonpie", num = 2, level = 3},
	{prefab = "taffy", num = 2, level = 3},
	{prefab = "pumpkincookie", num = 2, level = 3},
	{prefab = "kabobs", num = 2, level = 3},
	{prefab = "powcake", num = 2, level = 3},
	{prefab = "baconeggs", num = 2, level = 3},
	{prefab = "bonestew", num = 2, level = 3},
	{prefab = "ratatouille", num = 3, level = 3},
	{prefab = "fruitmedley", num = 2, level = 3},
	{prefab = "fishtacos", num = 2, level = 3},
	{prefab = "waffles", num = 1, level = 3},
	{prefab = "turkeydinner", num = 2, level = 3},
	{prefab = "fishsticks", num = 2, level = 3},
	{prefab = "stuffedeggplant", num = 2, level = 3},
	{prefab = "honeynuggets", num = 2, level = 3},
	{prefab = "meatballs", num = 4, level = 3},
	{prefab = "flowersalad", num = 1, level = 3},
	{prefab = "jammypreserves", num = 1, level = 3},
	{prefab = "icecream", num = 1, level = 3},
	{prefab = "watermelonicle", num = 2, level = 3},
	{prefab = "trailmix", num = 2, level = 3},
	{prefab = "guacamole", num = 2, level = 3},
	{prefab = "jellybean", num = 4, level = 3},
	{prefab = "healingsalve", num = 4, level = 3},
	{prefab = "bandage", num = 2, level = 3},
	{prefab = "walrus_tusk", num = 1, level = 3},
	{prefab = "bundlewrap", num = 1, level = 3},
	{prefab = "featherfan", num = 1, level = 3},
	{prefab = "gears", num = 5, level = 3},

	{prefab = "mandrake", num = 1, level = 4},
	{prefab = "mandrakesoup", num = 1, level = 4},
	{prefab = "armormarble", num = 1, level = 4},
	{prefab = "armorslurper", num = 1, level = 4},
	{prefab = "gunpowder", num = 5, level = 4},
	{prefab = "purplegem", num = 5, level = 4},
	{prefab = "bluegem", num = 6, level = 4},
	{prefab = "redgem", num = 6, level = 4},
	{prefab = "armor_sanity", num = 1, level = 4},
	{prefab = "nightsword", num = 1, level = 4},
	{prefab = "batbat", num = 1, level = 4},
	{prefab = "amulet", num = 1, level = 4},
	{prefab = "blueamulet", num = 1, level = 4},
	{prefab = "purpleamulet", num = 1, level = 4},
	{prefab = "firestaff", num = 1, level = 4},
	{prefab = "icestaff", num = 1, level = 4},
	{prefab = "telestaff", num = 1, level = 4},
	{prefab = "armordragonfly", num = 1, level = 4},
	{prefab = "staff_tornado", num = 1, level = 4},
	{prefab = "deserthat", num = 1, level = 4},
	{prefab = "steelwool", num = 4, level = 4},
	{prefab = "goose_feather", num = 4, level = 4},
	{prefab = "coffee", num = 4, level = 4},


	{prefab = "bearger_fur", num = 1, level = 5},
	{prefab = "minotaurhorn", num = 1, level = 5},
	{prefab = "deerclops_eyeball", num = 1, level = 5},
	{prefab = "livinglog", num = 5, level = 5},
	{prefab = "dragon_scales", num = 1, level = 5},
	{prefab = "shroom_skin", num = 1, level = 5},
	{prefab = "orangegem", num = 6, level = 5},
	{prefab = "yellowgem", num = 6, level = 5},
	{prefab = "greengem", num = 3, level = 5},
	{prefab = "thulecite", num = 10, level = 5},
	{prefab = "panflute", num = 1, level = 5},
	{prefab = "orangeamulet", num = 1, level = 5},
	{prefab = "yellowamulet", num = 1, level = 5},
	{prefab = "greenamulet", num = 1, level = 5},
	{prefab = "orangestaff", num = 1, level = 5},
	{prefab = "yellowstaff", num = 1, level = 5},
	{prefab = "greenstaff", num = 1, level = 5},
	{prefab = "ruinshat", num = 1, level = 5},
	{prefab = "armorruins", num = 1, level = 5},
	{prefab = "ruins_bat", num = 1, level = 5},
	{prefab = "hivehat", num = 1, level = 5},
	{prefab = "opalstaff", num = 1, level = 5},

	{prefab = "orangegem", num = 10, level = 6},
	{prefab = "yellowgem", num = 10, level = 6},
	{prefab = "greengem", num = 5, level = 6},
	{prefab = "thulecite", num = 30, level = 6},
	{prefab = "armorskeleton", num = 1, level = 6},
	--{prefab = "package_staff", num = 1, level = 6},
	{prefab = "pray_symbol", num = 1, level = 6},

	{prefab = "skillbookpage", num = 20, level = 7, novar = true},
}


--task reward
local collect_task_reward = {
	[1] = {
		{prefab = "blueprint", num = 1},
		{prefab = "diamond", num = 1},
		{prefab = "gunpowder", num = 5},
		{prefab = "purplegem", num = 5},
		{prefab = "bluegem", num = 5},
		{prefab = "redgem", num = 5},
		{prefab = "skillbookpage", num = 1},
		{prefab = "seeds", num = 20},
		{prefab = "coffee", num = 5},
		{prefab = "goldnugget", num = 15},
		{prefab = "ice", num = 15},
	},
	[2] = {
		{prefab = "diamond", num = 2},
		{prefab = "gunpowder", num = 5},
		{prefab = "bluegem", num = 10},
		{prefab = "redgem", num = 10},
		{prefab = "skillbookpage", num = 2},
		{prefab = "orangegem", num = 5},
		{prefab = "yellowgem", num = 5},
		{prefab = "greengem", num = 2},
		{prefab = "thulecite", num = 10},
		{prefab = "gears", num = 10},
		{prefab = "coffeebush", num = 2},
		{prefab = "honeycomb", num = 10},
		{prefab = "ghostflower", num = 10},
		{prefab = "wormlight", num = 5},
	},
	[3] = {
		{prefab = "blowdart_pipe", num = 10},
		{prefab = "diamond", num = 3},
		{prefab = "thulecite", num = 20},
		{prefab = "potion_luck", num = 2},
		{prefab = "potion_blue", num = 2},
		{prefab = "potion_red", num = 2},
		{prefab = "potion_green", num = 2},
		{prefab = "skillbookpage", num = 3},
		{prefab = "honeycomb", num = 20},
		{prefab = "wormlight", num = 10},
		{prefab = "goatmilk", num = 5},
		{prefab = "royal_jelly", num = 6},
		{prefab = "honey", num = 20},
		{prefab = "butter", num = 4},
	},
	[4] = {
		{prefab = "diamond", num = 4},
		{prefab = "skillbookpage", num = 4},
		{prefab = "meat_dried", num = 20},
		{prefab = "minotaurhorn", num = 2},
		{prefab = "deerclops_eyeball", num = 2},
		{prefab = "livinglog", num = 10},
		{prefab = "butter", num = 6},
		{prefab = "meatballs_spice_chili", num = 4},
		{prefab = "glowberrymousse_spice_garlic", num = 4},
		{prefab = "barnaclepita_spice_chili", num = 4},
		{prefab = "potatosouffle_spice_garlic", num = 4},
		{prefab = "frogfishbowl_spice_garlic", num = 4},
		{prefab = "gazpacho_spice_garlic", num = 4},
		{prefab = "dragonchilisalad_spice_garlic", num = 4},
		{prefab = "nightmarepie_spice_garlic", num = 4},
	},
	[5] = {
		{prefab = "diamond", num = 5},
		{prefab = "skillbookpage", num = 5},
		{prefab = "gears", num = 40},
		{prefab = "thulecite", num = 40},
		{prefab = "pray_symbol", num = 1},
		{prefab = "skillbook_1", num = 1},
		{prefab = "potatotornado_spice_salt", num = 5},
		{prefab = "pumpkincookie_spice_salt", num = 5},
		{prefab = "salsa_spice_salt", num = 5},
		{prefab = "vegstinger_spice_salt", num = 5},
		{prefab = "leafloaf_spice_salt", num = 5},
		{prefab = "voltgoatjelly_spice_salt", num = 5},
		{prefab = "surfnturf_spice_sugar", num = 5},
		{prefab = "ceviche_spice_sugar", num = 5},
		{prefab = "lobsterdinner_spice_sugar", num = 5},
		{prefab = "lobsterbisque_spice_sugar", num = 5},
		{prefab = "barnaclestuffedfishhead_spice_sugar", num = 5},
		{prefab = "barnaclinguine_spice_sugar", num = 5},
		{prefab = "barnaclepita_spice_sugar", num = 5},
	},
	[6] = {
		{prefab = "diamond", num = 10},
		{prefab = "skillbookpage", num = 8},
		{prefab = "skillbook_1", num = 1},
		{prefab = "skillbook_2", num = 1},
		{prefab = "skillbook_3", num = 1},
		--{prefab = "package_staff", num =1},
		{prefab = "linghterhat", num = 1},
		{prefab = "heisenberghat", num = 1},
		{prefab = "armordebroglie", num = 1},
	},
	[7] = {
		{prefab = "skillbook_2", num = 1},
		{prefab = "skillbook_3", num = 1},
		{prefab = "skillbook_4", num = 1},
	},
}

return {
	tasks = collect_task,
	rewards = collect_task_reward
}